networks:
  security_net:
    driver: bridge

services:
  thehive:
    image: strangebee/thehive:5.2
    depends_on:
      - cassandra
      - elasticsearch
      - minio
      - cortex
    networks:
      - security_net
    ports:
      - "9000:9000"   # HTTP
#      - "9443:9443"   # HTTPS (for SSL)
    environment:
      - JVM_OPTS=-Xms1024M -Xmx1024M
#      - PLAY_SERVER_HTTPS=true  # Enable HTTPS
#      - PLAY_SERVER_HTTPS_PORT=9443  # Use port 9443 for HTTPS
#      - PLAY_SERVER_HTTPS_CERTIFICATE=/etc/ssl/certs/cert.pem  # Path to the certificate
#      - PLAY_SERVER_HTTPS_CERTIFICATE_KEY=/etc/ssl/certs/cert.key  # Path to the key
    command:
      - --secret
      - "mySecretForTheHive"
      - "--cql-hostnames"
      - "cassandra"
      - "--index-backend"
      - "elasticsearch"
      - "--es-hostnames"
      - "elasticsearch"
      - "--s3-endpoint"
      - "http://minio:9000"
      - "--s3-access-key"
      - "minioadmin"
      - "--s3-secret-key"
      - "minioadmin"
      - "--s3-bucket"
      - "thehive"
      - "--s3-use-path-access-style"
      - "--cortex-hostnames"
      - "cortex"
      - "--cortex-keys"
      # put cortex api key once cortex is bootstraped
      - ""

    volumes:
      - /opt/PathtoThehiveDockercompose/thehive5-home:/home
      - /opt/PathtoThehiveDockercompose/thehive5-ssl/certs:/etc/ssl/certs  # Mount SSL certificates
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  cassandra:
    image: 'cassandra:4'
    networks:
      - security_net
    ports:
      - "9042:9042"
    environment:
      - MAX_HEAP_SIZE=1024M
      - HEAP_NEWSIZE=1024M
      - CASSANDRA_CLUSTER_NAME=TheHive
    volumes:
      - /opt/PathtoThehiveDockercompose/cassandra-data:/var/lib/cassandra
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.12
    networks:
      - security_net
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - /opt/PathtoThehiveDockercompose/elasticsearch-data:/usr/share/elasticsearch/data
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  minio:
    image: quay.io/minio/minio
    networks:
      - security_net
    command: ["minio", "server", "/data", "--console-address", ":9090"]
    environment:
      - MINIO_ROOT_USER=password
      - MINIO_ROOT_PASSWORD=password
    ports:
      - "9090:9090"
    volumes:
      - /opt/TheHiveCortex/minio-data:/data
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  cortex:
    image: thehiveproject/cortex:3.1.7
    depends_on:
      - elasticsearch
    networks:
      - security_net
    environment:
      - job_directory=/tmp/cortex-jobs
      - PLAY_SERVER_HTTPS=true  # Enable HTTPS
      - PLAY_SERVER_HTTPS_PORT=9444  # Use port 9444 for HTTPS
#      - PLAY_SERVER_HTTPS_CERTIFICATE=/etc/ssl/certs/cert.pem  # Path to the certificate
#      - PLAY_SERVER_HTTPS_CERTIFICATE_KEY=/etc/ssl/certs/cert.key  # Path to the key
    volumes:
      - /opt/PathtoThehiveDockercompose/cortex-tmp/cortex-jobs:/tmp/cortex-jobs
      - /opt/PathtoThehiveDockercompose/thehive5-home:/home
      - /opt/PathtoThehiveDockercompose/Cortex-Analyzers:/etc/cortex/analyzers
      - /opt/PathtoThehiveDockercompose/thehive5-home/application.conf:/etc/cortex/application.conf
      - /opt/PathtoThehiveDockercompose/thehive5-ssl/certs:/etc/ssl/certs  # Mount SSL certificates
    ports:
      - "9001:9001"  # HTTP
#      - "9444:9444"  # HTTPS (for SSL)
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  
